#!/usr/bin/env bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colours ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; BLUE='\033[0;34m'; YELLOW='\033[1;33m'; RESET='\033[0m'

echo ""
echo -e "${BLUE}claude-project-starter${RESET} — Claude Code config generator"
echo "────────────────────────────────────────────────"

# ── Project name ─────────────────────────────────────────────────────────────
read -rp "Project name: " PROJECT_NAME
if [[ -z "$PROJECT_NAME" ]]; then
  echo "Project name is required." && exit 1
fi

# ── Target directory ─────────────────────────────────────────────────────────
read -rp "Target directory [$(pwd)]: " TARGET_DIR
TARGET_DIR="${TARGET_DIR:-$(pwd)}"
TARGET_DIR="${TARGET_DIR/#\~/$HOME}"   # expand ~ if provided

if [[ ! -d "$TARGET_DIR" ]]; then
  read -rp "Directory '$TARGET_DIR' does not exist. Create it? [y/N]: " CREATE_DIR
  [[ "$CREATE_DIR" =~ ^[Yy]$ ]] && mkdir -p "$TARGET_DIR" || exit 1
fi

# ── Stack selection ───────────────────────────────────────────────────────────
STACKS=("python-fastapi" "react-vite" "node-express" "go")
SELECTED=()

echo ""
echo "Select stacks (enter numbers separated by spaces, e.g. 1 2):"
for i in "${!STACKS[@]}"; do
  echo "  $((i+1))) ${STACKS[$i]}"
done
echo "  0) None — base only"
echo ""
read -rp "Selection: " STACK_INPUT

if [[ "$STACK_INPUT" != "0" && -n "$STACK_INPUT" ]]; then
  for NUM in $STACK_INPUT; do
    IDX=$((NUM-1))
    if [[ $IDX -ge 0 && $IDX -lt ${#STACKS[@]} ]]; then
      SELECTED+=("${STACKS[$IDX]}")
    else
      echo -e "${YELLOW}Warning: '$NUM' is not a valid option — skipped${RESET}"
    fi
  done
fi

# ── Compose CLAUDE.md ─────────────────────────────────────────────────────────
CLAUDE_OUT="$TARGET_DIR/CLAUDE.md"

cat > "$CLAUDE_OUT" <<HEADER
# Project: $PROJECT_NAME

## Project
<!-- Fill in: what this project is, stack summary, key commands, design decisions -->

HEADER

cat "$SCRIPT_DIR/base/CLAUDE.md" >> "$CLAUDE_OUT"

for STACK in "${SELECTED[@]}"; do
  STACK_CLAUDE="$SCRIPT_DIR/stacks/$STACK/CLAUDE.md"
  if [[ -f "$STACK_CLAUDE" ]]; then
    echo "" >> "$CLAUDE_OUT"
    cat "$STACK_CLAUDE" >> "$CLAUDE_OUT"
  fi
done

# ── Compose .claudeignore ─────────────────────────────────────────────────────
IGNORE_OUT="$TARGET_DIR/.claudeignore"

cat > "$IGNORE_OUT" <<HEADER
# Generated by claude-project-starter — edit as needed
# Stacks: ${SELECTED[*]:-base only}

HEADER

cat "$SCRIPT_DIR/base/.claudeignore" >> "$IGNORE_OUT"

for STACK in "${SELECTED[@]}"; do
  STACK_IGNORE="$SCRIPT_DIR/stacks/$STACK/.claudeignore"
  if [[ -f "$STACK_IGNORE" ]]; then
    echo "" >> "$IGNORE_OUT"
    echo "# ── $STACK ──" >> "$IGNORE_OUT"
    cat "$STACK_IGNORE" >> "$IGNORE_OUT"
  fi
done

# ── Create ops/ directory ─────────────────────────────────────────────────────
OPS_DIR="$TARGET_DIR/ops"
mkdir -p "$OPS_DIR"
if [[ ! -f "$OPS_DIR/.gitkeep" && ! "$(ls -A "$OPS_DIR")" ]]; then
  touch "$OPS_DIR/.gitkeep"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Done.${RESET}"
echo ""
echo "  Created:"
echo "    $CLAUDE_OUT"
echo "    $IGNORE_OUT"
echo "    $OPS_DIR/"
if [[ ${#SELECTED[@]} -gt 0 ]]; then
  echo ""
  echo "  Stacks included: ${SELECTED[*]}"
fi
echo ""
echo "  Next steps:"
echo "    1. Fill in the ## Project section in CLAUDE.md"
echo "    2. Review .claudeignore — uncomment aggressive rules if applicable"
echo "    3. Start your Claude Code session"
echo ""
